import React, { useState, useEffect } from 'react'
import Head from 'next/head'
import { FaBars } from 'react-icons/fa'
import $ from 'jquery'
import Cookie, { useCookies } from 'react-cookie'

const Header = () => {
  let [url, setUrl] = useState('')
  const [isOpen, setIsOpen] = useState(true)
  const [cookies, setCookie] = useCookies(['user']);
  const [roles, setRoles] = useState('-1')

  useEffect(() => {
    $(document).ready(function () {
      $('body').addClass('loaded');
    })
  })

  useEffect(() => {
    if (cookies.user != undefined) {

      const userCookie = cookies.user
      setRoles(userCookie.roles)
    }
  })

  useEffect(() => {
    if (isOpen === true) {
      $('.menu-item').toggleClass('d-block w-100')
      $('.menu').toggleClass('text-center w-100')
    } else {
      $('.menu-item').toggleClass('d-block w-100')
      $('.menu').toggleClass('text-center w-100')
    }
  }, [isOpen])

  useEffect(() => {
    $(".bar-icon").click(() => {
      setIsOpen(!isOpen)
    })
  }, [isOpen])

  useEffect(() => {
    setUrl(window.location.pathname)
  }, [])
  var menu = [
    {
      name: 'Trang chủ',
      href: '/',
    },
    {
      name: 'Sản phẩm',
      href: '/san-pham',
    },
    {
      name: 'Bảng giá',
      href: '/bang-gia',
    },
    {
      name: 'Liên hệ',
      href: '/lien-he',
    },
    {
      name: 'Nhận báo giá',
      href: '/nhan-bao-gia',
    },
    {
      name: 'Admin',
      href: '/admin/tat-ca-xe',
    },
  ]
  return (
    <div className="header-group">
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.jpg" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossOrigin="anonymous"></link>
      </Head>
      <div className="header-top">
        <a href='/'>
          <img className="logo" src="https://dailysuzukicantho.com/OTO3602200370/files/logo.png" alt="" />
        </a>
      </div>
      <div className="header-content">
        <div className="menu position-relative">
          <span className='bar-icon position-absolute'>
            <FaBars />
          </span>
          {
            menu.map((item, index) => {
              if (item.href == url) {
                return <div className="menu-item" key={index}><a className="text-danger" href={item.href}>{item.name}</a></div>
              } if ((index === 4 && roles == 1) || (index === 4 && roles == 0)) {
                return <div className="menu-item" key={index}><a href="/profile">Profile</a></div>
              } if (index === 5 && roles !== 1) {
                return ''
              } else return <div className="menu-item" key={index}><a href={item.href}>{item.name}</a></div>
            })
          }
        </div>
      </div>
      <div id="loader-wrapper">
        <div id="loader"></div>
        <div className="loader-section section-left"></div>
        <div className="loader-section section-right"></div>
      </div>
    </div>
  )
}

export default Header